// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Api.Data;

namespace Routine.Api.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20200308124059_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Routine.Api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            Country = "USA",
                            Industry = "Software",
                            Introduction = "Great Company",
                            Name = "Microsoft",
                            Product = "Software"
                        },
                        new
                        {
                            Id = new Guid("1544a292-1c80-4595-bc4a-2a4952fc5c1f"),
                            Country = "USA",
                            Industry = "Internet",
                            Introduction = "Don't be evil",
                            Name = "Google",
                            Product = "Software"
                        },
                        new
                        {
                            Id = new Guid("d030761a-7ab4-4235-9232-def88be14d4a"),
                            Country = "China",
                            Industry = "Internet",
                            Introduction = "Fubao Company",
                            Name = "Alipapa",
                            Product = "Software"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("companyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("employeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("companyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9665c8ef-03d4-4af1-87bc-d84cdaded5f5"),
                            Gender = 1,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("bc4873aa-623f-4069-96a4-76c323f39e82"),
                            Gender = 2,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("d2f3d4bd-984a-49f9-9dfc-394cd204158b"),
                            Gender = 1,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("43f76027-229b-435f-95f6-d47fa4f8e7d5"),
                            Gender = 2,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("5ff6be02-52cd-4914-af1f-b6b1f73dffdd"),
                            Gender = 1,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("14427c90-cc70-421a-a25d-11f9e3a1e5a7"),
                            Gender = 2,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("c5f415f7-edf8-4894-99f3-08c35e80f871"),
                            Gender = 1,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("75d0c702-cf15-4064-a7c9-f58685be0d94"),
                            Gender = 2,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1wckk9NbrGGUSZU4",
                            firstName = "Bruce",
                            lastName = "Forster"
                        },
                        new
                        {
                            Id = new Guid("12bcfa41-5b5c-45e9-aa34-5a7a52183584"),
                            Gender = 2,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "VU7yqFzVUXqnVJyU",
                            firstName = "Donald",
                            lastName = "Washington"
                        },
                        new
                        {
                            Id = new Guid("d51d5aa1-2329-4e40-8573-4a8ddb520c18"),
                            Gender = 1,
                            companyId = new Guid("da7ee895-bb98-4b80-b0f1-d9d86fef8c95"),
                            dateOfBirth = new DateTime(1958, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "1RewsGnQdvozB0cb",
                            firstName = "Vito",
                            lastName = "Evans"
                        },
                        new
                        {
                            Id = new Guid("bc7d1bbd-bd48-413d-95e7-c8f800e32629"),
                            Gender = 2,
                            companyId = new Guid("1544a292-1c80-4595-bc4a-2a4952fc5c1f"),
                            dateOfBirth = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "huHM1OcqoLLpyL0X",
                            firstName = "Polly",
                            lastName = "Salome"
                        },
                        new
                        {
                            Id = new Guid("e9d3f23d-c71d-4c12-bcc2-a9554ba50396"),
                            Gender = 1,
                            companyId = new Guid("d030761a-7ab4-4235-9232-def88be14d4a"),
                            dateOfBirth = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "g7BSz9HJZoJui5wr",
                            firstName = "Len",
                            lastName = "Partridge"
                        },
                        new
                        {
                            Id = new Guid("053988cc-05b4-4bf5-8c24-ea826d5ee90d"),
                            Gender = 2,
                            companyId = new Guid("1544a292-1c80-4595-bc4a-2a4952fc5c1f"),
                            dateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "Zpsy9IdWEc6kdrhQ",
                            firstName = "Adair",
                            lastName = "Kent"
                        },
                        new
                        {
                            Id = new Guid("3c3fe8ec-c441-4855-83cd-ea9e3cf60fc9"),
                            Gender = 1,
                            companyId = new Guid("d030761a-7ab4-4235-9232-def88be14d4a"),
                            dateOfBirth = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "I4nNzk1ezsuSEaVC",
                            firstName = "Bernice",
                            lastName = "Harold"
                        },
                        new
                        {
                            Id = new Guid("a035c368-1171-4633-baee-fcfa31bf9b3b"),
                            Gender = 2,
                            companyId = new Guid("1544a292-1c80-4595-bc4a-2a4952fc5c1f"),
                            dateOfBirth = new DateTime(1975, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            employeeNo = "NO9drmGvuBM9hBom",
                            firstName = "Edison",
                            lastName = "Thackeray"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Api.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
